name: leaflet_map
description: Leaflet Map ported to Dart
version: 0.0.1
homepage: https://github.com/zyzbroker/leaflet-map-dart-library

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  tuple: ^1.0.3
  quiver: ^2.1.3

dev_dependencies:
  build_runner: ^1.10.3
  path: ^1.7.0
  build_test: ^1.2.2
  build_web_compilers: ^2.12.2
  collection: ^1.14.13
  test: ^1.15.4
  sass_builder: ^2.1.3
